import 'roadmap.dart';

final List<Topic> sampleTopics = [
  Topic(
    id: 'topic-flutter',
    title: 'Flutter Development',
    description: 'Lộ trình học phát triển ứng dụng di động đa nền tảng với Flutter và Dart.',
    emoji: '📱',
    createdAt: DateTime(2026, 1, 1).toIso8601String(),
    lessons: [
      Lesson(
        id: 'lesson-dart-basics',
        topicId: 'topic-flutter',
        title: 'Dart Programming Basics',
        description: 'Học ngôn ngữ Dart, nền tảng của Flutter, từ cơ bản đến nâng cao.',
        order: 1,
        nodes: [
          StepNode(
            id: 'step-dart-1',
            lessonId: 'lesson-dart-basics',
            title: 'Variables & Basic Types / Biến & Kiểu dữ liệu',
            description: 'Tìm hiểu cách khai báo biến, các kiểu dữ liệu cơ bản như String, int, double, bool và từ khóa var, final, const.',
            emoji: '📦',
            positionX: 200,
            positionY: 100,
            status: StepStatus.completed,
            order: 1,
          ),
          StepNode(
            id: 'step-dart-2',
            lessonId: 'lesson-dart-basics',
            title: 'Operators & Functions / Toán tử & Hàm',
            description: 'Cách sử dụng toán tử số học, logic, so sánh và viết các hàm có tham số tùy chọn hoặc đặt tên.',
            emoji: '⚙️',
            positionX: 500,
            positionY: 220,
            status: StepStatus.completed,
            order: 2,
          ),
          StepNode(
            id: 'step-dart-3',
            lessonId: 'lesson-dart-basics',
            title: 'Control Flow (If/Else, Loops) / Cấu trúc rẽ nhánh & Vòng lặp',
            description: 'Sử dụng If-Else, Switch Case, vòng lặp for, while để điều khiển luồng chương trình.',
            emoji: '🔄',
            positionX: 200,
            positionY: 340,
            status: StepStatus.inProgress,
            order: 3,
          ),
          StepNode(
            id: 'step-dart-4',
            lessonId: 'lesson-dart-basics',
            title: 'Object-Oriented Programming (OOP) / Hướng đối tượng',
            description: 'Hiểu về Class, Object, Kế thừa (Inheritance), Đa hình (Polymorphism), Mixins và Interfaces trong Dart.',
            emoji: '🧩',
            positionX: 500,
            positionY: 460,
            status: StepStatus.notStarted,
            order: 4,
          ),
          StepNode(
            id: 'step-dart-5',
            lessonId: 'lesson-dart-basics',
            title: 'Asynchronous (Future, Stream) / Lập trình bất đồng bộ',
            description: 'Làm chủ async, await, Future và Stream để xử lý các tác vụ tốn thời gian như gọi API hoặc đọc file.',
            emoji: '⚡',
            positionX: 350,
            positionY: 580,
            status: StepStatus.notStarted,
            order: 5,
          ),
        ],
        edges: [
          Edge(id: 'edge-dart-1', lessonId: 'lesson-dart-basics', from: 'step-dart-1', to: 'step-dart-2'),
          Edge(id: 'edge-dart-2', lessonId: 'lesson-dart-basics', from: 'step-dart-2', to: 'step-dart-3'),
          Edge(id: 'edge-dart-3', lessonId: 'lesson-dart-basics', from: 'step-dart-3', to: 'step-dart-4'),
          Edge(id: 'edge-dart-4', lessonId: 'lesson-dart-basics', from: 'step-dart-4', to: 'step-dart-5'),
        ],
      ),
      Lesson(
        id: 'lesson-flutter-ui',
        topicId: 'topic-flutter',
        title: 'Flutter UI & Widgets',
        description: 'Xây dựng giao diện người dùng đẹp mắt với hệ thống Widget của Flutter.',
        order: 2,
        nodes: [
          StepNode(
            id: 'step-ui-1',
            lessonId: 'lesson-flutter-ui',
            title: 'Stateless vs Stateful Widgets',
            description: 'Sự khác biệt cốt lõi giữa Widget không trạng thái và Widget có trạng thái, khi nào nên dùng cái nào.',
            emoji: '🎨',
            positionX: 200,
            positionY: 100,
            status: StepStatus.notStarted,
            order: 1,
          ),
          StepNode(
            id: 'step-ui-2',
            lessonId: 'lesson-flutter-ui',
            title: 'Basic Widgets (Text, Image, Container)',
            description: 'Thành thạo các widget cơ bản để vẽ và trang trí layout cơ bản.',
            emoji: '🖼️',
            positionX: 500,
            positionY: 220,
            status: StepStatus.notStarted,
            order: 2,
          ),
          StepNode(
            id: 'step-ui-3',
            lessonId: 'lesson-flutter-ui',
            title: 'Layout Widgets (Row, Column, Stack)',
            description: 'Cách sắp xếp các widget theo hàng ngang, cột dọc hoặc đè lên nhau.',
            emoji: '📊',
            positionX: 200,
            positionY: 340,
            status: StepStatus.notStarted,
            order: 3,
          ),
        ],
        edges: [
          Edge(id: 'edge-ui-1', lessonId: 'lesson-flutter-ui', from: 'step-ui-1', to: 'step-ui-2'),
          Edge(id: 'edge-ui-2', lessonId: 'lesson-flutter-ui', from: 'step-ui-2', to: 'step-ui-3'),
        ],
      ),
    ],
  ),
  Topic(
    id: 'topic-java',
    title: 'Java Programming',
    description: 'Lộ trình học lập trình hướng đối tượng Java toàn diện cho backend developer.',
    emoji: '📘',
    createdAt: DateTime(2026, 1, 5).toIso8601String(),
    lessons: [
      Lesson(
        id: 'lesson-java-intro',
        topicId: 'topic-java',
        title: 'Java Core Fundamentals',
        description: 'Làm quen với cú pháp Java, kiểu dữ liệu và cấu trúc điều khiển.',
        order: 1,
        nodes: [
          StepNode(
            id: 'step-java-1',
            lessonId: 'lesson-java-intro',
            title: 'JDK, JRE & JVM / Cài đặt môi trường',
            description: 'Hiểu kiến trúc chạy mã Java, cài đặt JDK và viết chương trình HelloWorld đầu tiên.',
            emoji: '💻',
            positionX: 200,
            positionY: 100,
            status: StepStatus.completed,
            order: 1,
          ),
          StepNode(
            id: 'step-java-2',
            lessonId: 'lesson-java-intro',
            title: 'Data Types & Variables / Kiểu dữ liệu',
            description: 'Kiểu dữ liệu nguyên thủy (primitive) và kiểu đối tượng (reference) trong Java.',
            emoji: '🔢',
            positionX: 500,
            positionY: 220,
            status: StepStatus.completed,
            order: 2,
          ),
          StepNode(
            id: 'step-java-3',
            lessonId: 'lesson-java-intro',
            title: 'Conditional Statements / Cấu trúc rẽ nhánh',
            description: 'Làm quen với if-else, ternary operator và switch-case truyền thống.',
            emoji: '🌿',
            positionX: 200,
            positionY: 340,
            status: StepStatus.inProgress,
            order: 3,
          ),
        ],
        edges: [
          Edge(id: 'edge-java-1', lessonId: 'lesson-java-intro', from: 'step-java-1', to: 'step-java-2'),
          Edge(id: 'edge-java-2', lessonId: 'lesson-java-intro', from: 'step-java-2', to: 'step-java-3'),
        ],
      ),
    ],
  ),
];

final List<ClassGroup> sampleClasses = [
  ClassGroup(
    id: "class-1",
    name: "Lập trình di động K22 (Flutter)",
    code: "LTM-F-K22",
    room: "Lab 302",
    createdAt: "2026-01-10T00:00:00.000Z",
  ),
  ClassGroup(
    id: "class-2",
    name: "Lập trình Web nâng cao (React/Node)",
    code: "WEB-ADV-K21",
    room: "Lab 105",
    createdAt: "2026-02-15T00:00:00.000Z",
  ),
  ClassGroup(
    id: "class-3",
    name: "Học máy & Khoa học dữ liệu K20",
    code: "ML-DS-01",
    room: "Phòng 402",
    createdAt: "2026-03-01T00:00:00.000Z",
  ),
];

final List<Student> sampleStudents = [
  Student(
    id: "stud-1",
    classId: "class-1",
    name: "Nguyễn Văn Đạt",
    studentId: "SV202601",
    avatarEmoji: "🦊",
    avatarColor: "#f97316",
    photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=60",
    password: "123",
    createdAt: "2026-01-11T00:00:00.000Z",
  ),
  Student(
    id: "stud-2",
    classId: "class-1",
    name: "Lê Minh Thư",
    studentId: "SV202602",
    avatarEmoji: "🦄",
    avatarColor: "#ec4899",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=60",
    password: "123",
    createdAt: "2026-01-11T00:00:00.000Z",
  ),
  Student(
    id: "stud-3",
    classId: "class-1",
    name: "Trần Thế Bảo",
    studentId: "SV202603",
    avatarEmoji: "🦁",
    avatarColor: "#eab308",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=60",
    password: "123",
    createdAt: "2026-01-12T00:00:00.000Z",
  ),
  Student(
    id: "stud-4",
    classId: "class-2",
    name: "Phạm Hồng Ngọc",
    studentId: "SV202604",
    avatarEmoji: "🌸",
    avatarColor: "#f43f5e",
    photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=60",
    password: "123",
    createdAt: "2026-02-16T00:00:00.000Z",
  ),
  Student(
    id: "stud-5",
    classId: "class-2",
    name: "Vũ Quốc Khánh",
    studentId: "SV202605",
    avatarEmoji: "🐼",
    avatarColor: "#64748b",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=60",
    password: "123",
    createdAt: "2026-02-16T00:00:00.000Z",
  ),
  Student(
    id: "stud-6",
    classId: "class-3",
    name: "Hoàng Thanh Hà",
    studentId: "SV202606",
    avatarEmoji: "🐨",
    avatarColor: "#06b6d4",
    photoUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=60",
    password: "123",
    createdAt: "2026-03-02T00:00:00.000Z",
  ),
];

